name: mr_collection
description: "集金くん"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.1.4
  freezed: ^2.2.0
  json_serializable: ^6.6.0

flutter:
  assets: 
    - assets/icons/filter.svg
    - assets/icons/circle_plus.svg
    - assets/icons/settings.svg
    - assets/icons/flag.svg
    - assets/icons/sad_face.svg
    - assets/icons/close_circle.svg
    - assets/icons/check_circle.svg
    - assets/icons/line.svg
    - assets/icons/delete.svg
    - assets/icons/plus.svg

  uses-material-design: true
